version: 2
updates:
- package-ecosystem: npm
  directory: "/react-demo"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
